[project]
name = "transcribee-worker"
version = "0.1.0"
description = "a transcription worker for the transcribee open-source transcription platform"
authors = [
    { name = "anuejn", email = "jarohabiger@googlemail.com" },
    { name = "pajowu", email = "git@ca.pajowu.de" },
    { name = "phlmn", email = "info@philipp-mandler.com" },
    { name = "vup", email = "robin.ole.heinemann+transcribee@gmail.com" },
]

dependencies = [
    "transcribee-proto @ file:///${PROJECT_ROOT}/../proto",
    "numpy>=1.23.5",
    "librosa>=0.10.0",
    "pydantic>=1.10.5",
    "whispercpp @ git+https://github.com/transcribee/whispercpp.git@pajowu/wip",
    "transformers>=4.26.1",
    "torchaudio>=0.13.1",
    "torch>=1.13.1",
    "automerge @ git+https://github.com/transcribee/automerge-py.git@5488f418edf52a5be7d61f7ae08c3a4721a233a1",
    "websockets>=10.4",
]
requires-python = ">=3.10"
readme = "README.md"
license = { text = "AGPL-3.0" }

[tool.pdm.dev-dependencies]
dev = ["black>=23.1.0"]

[tool.pdm.scripts]
start = "python run.py"

[build-system]
requires = ["pdm-pep517>=1.0"]
build-backend = "pdm.pep517.api"
